"""Convert float fields to integer

Revision ID: 42e0143b1ae1
Revises: 93d31f310a73
Create Date: 2025-05-07 17:24:21.611973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e0143b1ae1'
down_revision = '93d31f310a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('electricity',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('shopping', schema=None) as batch_op:
        batch_op.alter_column('furniture_appliances',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('clothing',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('entertainment',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('office_supplies',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('personal_care',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('services_food',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('communication',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('loan',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('transport',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.alter_column('public_transit_distance',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('air_travel_distance',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('bus_kms',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('transit_rail_kms',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('commuter_rail_kms',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('intercity_rail_kms',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.alter_column('intercity_rail_kms',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('commuter_rail_kms',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('transit_rail_kms',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('bus_kms',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('air_travel_distance',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('public_transit_distance',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('shopping', schema=None) as batch_op:
        batch_op.alter_column('transport',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('loan',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('communication',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('services_food',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('personal_care',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('office_supplies',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('entertainment',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('clothing',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('furniture_appliances',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('electricity',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
