"""Update on Emission table

Revision ID: 4ac5c716c889
Revises: 0a06f4727f1f
Create Date: 2025-05-02 16:32:33.166753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac5c716c889'
down_revision = '0a06f4727f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('air_travel_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('public_transit_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('water_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heating_fuels_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('construction_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('electricity_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('natural_gas_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('meat_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dairy_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fruits_vegetables_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cereals_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('snacks_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clothing_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('furniture_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_goods_emissions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('services_emissions', sa.Float(), nullable=True))
        batch_op.drop_column('home_emissions')
        batch_op.drop_column('travel_emissions')
        batch_op.drop_column('shopping_emissions')
        batch_op.drop_column('food_emissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_emissions', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('shopping_emissions', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('travel_emissions', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('home_emissions', sa.FLOAT(), nullable=True))
        batch_op.drop_column('services_emissions')
        batch_op.drop_column('other_goods_emissions')
        batch_op.drop_column('furniture_emissions')
        batch_op.drop_column('clothing_emissions')
        batch_op.drop_column('snacks_emissions')
        batch_op.drop_column('cereals_emissions')
        batch_op.drop_column('fruits_vegetables_emissions')
        batch_op.drop_column('dairy_emissions')
        batch_op.drop_column('meat_emissions')
        batch_op.drop_column('natural_gas_emissions')
        batch_op.drop_column('electricity_emissions')
        batch_op.drop_column('construction_emissions')
        batch_op.drop_column('heating_fuels_emissions')
        batch_op.drop_column('water_emissions')
        batch_op.drop_column('public_transit_emissions')
        batch_op.drop_column('air_travel_emissions')
        batch_op.drop_column('car_emissions')

    # ### end Alembic commands ###
