"""add_email_confirmation_and_password_reset

Revision ID: 9149a9337563
Revises: e6aec94cfb48
Create Date: 2025-05-01 13:30:27.747027

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9149a9337563'
down_revision = 'e6aec94cfb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
