"""Added unconfirmed_email column to user

Revision ID: a494c707198b
Revises: 93d31f310a73
Create Date: 2025-05-10 00:23:36.657917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a494c707198b'
down_revision = '93d31f310a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unconfirmed_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_unconfirmed_email', ['unconfirmed_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unconfirmed_email')

    # ### end Alembic commands ###
